### ISSUE TITLE
need a way to restore the old "core" (index)

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud.solr#86]
Now that we're not running solr in its own directory and saving the indexed notebooks there, we need a way (either in rcloud.solr installation instructions or better in the config) to point to the core/index so that we can restart the service and have it pick up where it left off.

@s-u writes

> The current SOLR setup won't persist a core that is created, i.e. after a restart the core is not available anymore.
This is due to dynamic core detection since SOLR 4.4 which means that cores are not specified in the config file but found in the file system.
However, the core for rcloudnotebooks is not under SOLR_HOME so it won't be fount.
The fix is to symlink the solrdata into SOLR_HOME so it is included in the search:

> ln -s ../../../solrdata/solr $DEST/solr/server/solr/cores

> A proper solution would be to move SOLR_HOME from $DEST/solr/server/solr to solrdata

This is the remaining issue so that we can release 1.9.1 to the rest of the company.

**Comment by dougmet** [comment]
I'm on this today.

**Comment by dougmet** [comment]
If I've understood correctly then we need to add the `solrdata` directory to the solrconfig.xml [here](https://github.com/att/rcloud/blob/06ce34e0eb3ee549cef19195648760956440f2ae/conf/solr/solrconfig.xml#L96)

**Comment by dougmet** [comment]
OK, it looks easier than that. Just going to run sol from the solrdata directory. Just need to make sure there's a `solr.xml` file in there and solr will pick up the cores. Then it's

```sh
solr start -s /data/rcloud/solrdata
```

or replace the path with a suitable environment variable

**Comment by gordonwoodhull** [comment]
Thanks @dougmet! Fixed in RCloud 1.9.1
